<!DOCTYPE HTML>
<HTML>
<HEAD>
	<TITLE>PHP FORMS</TITLE>
</HEAD>
<BODY>
	<FORM ACTION="FORM_PROCESS.PHP" METHOD="POST">
	<INPUT TYPE="TEXT" NAME="USERNAME" PLACEHOLDER="ENTER USERNAME" />
	<INPUT TYPE="PASSWORD" NAME="PASSWORD" PLACEHOLDER="ENTER PASSWORD" />
	<BR />
	<INPUT TYPE="SUBMIT" NAME="SUBMIT" />
</FORM>
</BODY>
</HTML>
